### ISSUE TITLE
Add Playwright Testcontainers

### ISSUE THREAD

**Issue by collabnix** [collabnix/awesome-testcontainers#35]
This library provides a [Testcontainers](https://www.testcontainers.org/)-based container for [Playwright](https://playwright.dev/java/) that enables running browser automation and testing without installing Playwright browsers locally.

It offers a low-level API to directly work with the container and a high-level API via JUnit 5 extension for seamless integration with your tests.

https://github.com/orange-buffalo/testcontainers-playwright

**Comment by Adesoji1** [comment]
@collabnix  That's true and  i wrote a blog about it too : https://collabnix.com/streamline-browser-automation-1-powerful-way-with-testcontainers-playwright/

**Comment by Adesoji1** [comment]
Added to the repo
