### ISSUE TITLE
Add a blog - Testcontainers MongoDB ReplicaSet

### ISSUE THREAD

**Issue by ajeetraina** [collabnix/awesome-testcontainers#45]
https://dev.to/carc/testcontainers-mongodb-replicaset-4koa

Testcontainers provides a built-in [MongoDB container](https://java.testcontainers.org/modules/databases/mongodb/) that consists of a single-node replica set. This is convenient for simple tests. However, for scenarios requiring a multi-node MongoDB cluster, we encounter a challenge. While Testcontainers recommends an external library—https://github.com/silaev/mongodb-replica-set/—this solution appears to be abandoned at the time of writing.

In this article, we'll explore how to create a simple multi-node MongoDB replica set using Testcontainers and discuss the challenges we'll face along the way.

**Comment by Adesoji1** [comment]
done
