### ISSUE TITLE
BAdges not refreshing

### ISSUE THREAD

**Issue by Adesoji1** [collabnix/awesome-testcontainers#52]
![stars](https://img.shields.io/github/stars/collabnix/awesome-testcontainers)
![forks](https://img.shields.io/github/forks/collabnix/awesome-testcontainers)
![issues](https://img.shields.io/github/issues/collabnix/awesome-testcontainers)
![Twitter](https://img.shields.io/twitter/follow/testcontainers?style=social)  @mdelapenya  what can we do about this?

**Comment by mdelapenya** [comment]
I see the badges refreshing, what do you see on your side?

**Comment by alwinhb** [comment]
I see this issue but looks like it is intermittent, Looks like an issue from cloud-flare.
![Worked](https://github.com/user-attachments/assets/d4fd5dba-e54c-462b-ae60-87ab66cdd35b)
