### ISSUE TITLE
Add Go library for Tigerbeetle integration testing

### ISSUE THREAD

**Issue by ajeetraina** [collabnix/awesome-testcontainers#54]
[@TigerBeetleDB](https://x.com/TigerBeetleDB) is a distributed financial accounting database designed for mission-critical safety and performance.

Here's a Go library for Tigerbeetle integration testing via 
[@Testcontainers](https://x.com/testcontainers)

https://github.com/mkadirtan/testcontainers-tigerbeetle-go?tab=readme-ov-file

**Comment by Adesoji1** [comment]
@ajeetraina  done
